### PR TITLE
Reuse feel engine for all connector functions

### PR DESCRIPTION
**Pull request by menski**
## Description

Instead of creating a new feel engine per connector reuse it for all connector functions.

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
Looks good to me, good idea to reuse the FEEL engine 👍

**Comment by nikku** [comment]
@menski This changes our public API.

As the connector function wrapper is public API, this change leaks internals into our API surface. We should remedy this somehow.

If we introduce breaking changes, let us please also mark this as a breaking change in the commit next time:

```
foo: do stuff

BREAKING CHANGES:

* this and that changed, this is how to remedy
```

(Cf. [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)).

However we fix this we should follow up with documentation adjustments (https://github.com/camunda/connector-sdk/tree/main/runtime-job-worker#wrapping-a-connector-function): Either remove the _run yourself_ code snippet, or make the FEEL engine wrapper public API.

----

On another note I'd apprechiate if you could add a little bit of background to such a PR: Why is it something we want to do? Performance improvement? Code style?

**Comment by nikku** [comment]
Is https://github.com/camunda/team-connectors/issues/125 the context for the PR?

**Comment by nikku** [comment]
Alternative: Make `FeelEngineWrapper` a singleton.

**Comment by tmetzke** [comment]
OK, it was obviously too late yesterday evening. Good points, @nikku 👍 
Should we revert this for now? Should we move forward with this by making the wrapper public API?
I am holding back the release for now.

**Comment by nikku** [comment]
> Alternative: Make FeelEngineWrapper a singleton.

That is a simple workaround / alternative.

**Comment by menski** [comment]
> Is https://github.com/camunda/team-connectors/issues/125 the context for the PR?

No the context is https://github.com/camunda/team-connectors/issues/99, where we try to bundle all connectors in a single runtime, which creates a FeelEngine for each connector. Sorry for not providing enough context.

**Comment by tmetzke** [comment]
I reverted this with https://github.com/camunda/connector-sdk/commit/a139c99a0bc99f0641fd69d3cb54decc113420e3.
@menski, please create a follow-up issue for this.
See the discussion on Slack here: https://camunda.slack.com/archives/C0350959WG1/p1664222461893879

**Comment by menski** [comment]
Follow up issue: https://github.com/camunda/connector-sdk/issues/121

**Pull request merged**
