### PR TITLE
Cancellation callback, activation condition and variable mappings

### PR DESCRIPTION
**Pull request by chillleader**
## Description

Introduced the following changes to Connector SDK:

- **Support cancellation callback for inbound connectors** (#393). This is needed to handle external errors that may happen with active inbound connectors, e.g. network errors that result in subscription failure.
- **Moved `activationCondition` and `variableMapping` properties handling to the SDK/Runtime level** (#412). Variable mapping field was replaced with 2 fields: `resultExpression` and `resultVariable`.
  - Now the Runtime supports a similar field set for inbound and outbound connectors for mapping variables (`resultVariable` and `resultExpression`, providing identical behavior for both types of connectors.
- Other general improvements:
  - Error handling was improved (now business errors like activation condition mismatch don't result in exception being thrown, plus replaced the generic `Object` type of `responseData` in `InboundConnectorResult`).
  - Minor adjustments to javadocs
  - Removed `SubscriptionInboundConnector` abstract class (likely not needed, doesn't add much value)

## Related issues

related to #393, #412

### CODE REVIEW

**Comment by chillleader** [comment]
Need to rework a few things around `activationCondition` and `variableMapping`

**Review by igpetrov — APPROVED** [review]
LGTM. Since some classes changed their packages, do you expect this change to be with breaking changes?

If so, let's move it faster so that we have time to test runtime and connectors.

**Comment by igpetrov** [comment]
also, @chillleader, shall we squash into 1 commit or do you want to keep those as 4?

**Comment by chillleader** [comment]
@igpetrov there are a couple of changes required in spring-zeebe after this, I'm planning to open a PR in spring-zeebe today or tomorrow supporting these changes.

**Comment by igpetrov** [comment]
@chillleader perfect, thanks for explanation. We just found an issue with Spring Zeebe migration in alpha3 build - breaking changes from [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/372) but @markfarkas-camunda is already on it.

**Pull request merged**
