### PR TITLE
chore: packed 0.3.0 runtime in docker

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

Packed 0.3.0 runtime in docker

## Related issues

#222

### CODE REVIEW

**Comment by igpetrov** [comment]
Did a test build with `docker build -t runtime222:999.0.0 .`

Output on start:

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.5)

2022-11-02 16:50:01.854  INFO 1 --- [           main] o.s.boot.SpringApplication               : Starting application using Java 17.0.4 on b50741295298 with PID 1 (started by root in /)
2022-11-02 16:50:01.855  INFO 1 --- [           main] o.s.boot.SpringApplication               : No active profile set, falling back to 1 default profile: "default"
2022-11-02 16:50:02.199  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.camunda.zeebe.spring.client.annotation.processor.AnnotationProcessorConfiguration' of type [io.camunda.zeebe.spring.client.annotation.processor.AnnotationProcessorConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.202  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'deploymentPostProcessor' of type [io.camunda.zeebe.spring.client.annotation.processor.ZeebeDeploymentAnnotationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.203  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration' of type [io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.206  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'commandExceptionHandlingStrategy' of type [io.camunda.zeebe.spring.client.jobhandling.DefaultCommandExceptionHandlingStrategy] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.208  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'secretStore' of type [io.camunda.connector.api.secret.SecretStore] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.284  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zeebe.client-io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties' of type [io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.286  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration' of type [io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration$$EnhancerBySpringCGLIB$$2f3c400e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.293  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zeebeJsonMapper' of type [io.camunda.zeebe.client.impl.ZeebeObjectMapper] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.293  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jobWorkerManager' of type [io.camunda.zeebe.spring.client.jobhandling.JobWorkerManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.294  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'outboundConnectorAnnotationProcessor' of type [io.camunda.zeebe.spring.client.annotation.processor.OutboundConnectorAnnotationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.295  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'propertyBasedZeebeWorkerValueCustomizer' of type [io.camunda.zeebe.spring.client.properties.PropertyBasedZeebeWorkerValueCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.296  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zeebeWorkerPostProcessor' of type [io.camunda.zeebe.spring.client.annotation.processor.ZeebeWorkerAnnotationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 16:50:02.365  INFO 1 --- [           main] i.c.z.s.c.ZeebeClientSpringConfiguration : Creating ZeebeClient using ZeebeClientBuilder [gatewayAddress: 0.0.0.0:26500
jobWorkerMaxJobsActive: 32
numJobWorkerExecutionThreads: 1
defaultJobWorkerName: null
defaultJobTimeout: PT5M
defaultJobPollInterval: PT0.1S
defaultMessageTimeToLive: PT1H
defaultRequestTimeout: PT10S
overrideAuthority: null
]
2022-11-02 16:50:02.579  INFO 1 --- [           main] a.p.OutboundConnectorAnnotationProcessor : Reading environment variables or parsing SPI to find connectors that are not Spring beans
2022-11-02 16:50:02.580  INFO 1 --- [           main] .u.o.OutboundConnectorRegistrationHelper : Parsing SPI to find connectors that are not Spring beans
2022-11-02 16:50:02.584  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'zeebeClientLifecycle'; nested exception is java.lang.NoSuchMethodError: 'void io.camunda.connector.impl.outbound.OutboundConnectorConfiguration.<init>(java.lang.String, java.lang.String, java.lang.String[], io.camunda.connector.api.outbound.OutboundConnectorFunction)'
2022-11-02 16:50:02.590  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-02 16:50:02.600 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.camunda.connector.runtime.util.outbound.OutboundConnectorRegistrationHelper.lambda$parseFromSPI$1(OutboundConnectorRegistrationHelper.java:99)

The following method did not exist:

    'void io.camunda.connector.impl.outbound.OutboundConnectorConfiguration.<init>(java.lang.String, java.lang.String, java.lang.String[], io.camunda.connector.api.outbound.OutboundConnectorFunction)'

The calling method's class, io.camunda.connector.runtime.util.outbound.OutboundConnectorRegistrationHelper, was loaded from the following location:

    jar:file:/opt/app/connector-runtime-0.3.0-SNAPSHOT-with-dependencies.jar!/io/camunda/connector/runtime/util/outbound/OutboundConnectorRegistrationHelper.class

The called method's class, io.camunda.connector.impl.outbound.OutboundConnectorConfiguration, is available from the following locations:

    jar:file:/opt/app/connector-sqs-0.2.0-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class
    jar:file:/opt/app/connector-slack-0.4.0-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class
    jar:file:/opt/app/connector-sendgrid-0.11.0-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class
    jar:file:/opt/app/connector-http-json-0.9.0-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class
    jar:file:/opt/app/connector-google-drive-0.4.0-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class
    jar:file:/opt/app/connector-aws-lambda-0.3.2-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class
    jar:file:/opt/app/connector-runtime-0.3.0-SNAPSHOT-with-dependencies.jar!/io/camunda/connector/impl/outbound/OutboundConnectorConfiguration.class

The called method's class hierarchy was loaded from the following locations:

    io.camunda.connector.impl.outbound.OutboundConnectorConfiguration: file:/opt/app/connector-sqs-0.2.0-with-dependencies.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes io.camunda.connector.runtime.util.outbound.OutboundConnectorRegistrationHelper and io.camunda.connector.impl.outbound.OutboundConnectorConfiguration


```

**Comment by igpetrov** [comment]
With updated runtime version - expected output:

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.5)

2022-11-02 17:05:34.558  INFO 1 --- [           main] o.s.boot.SpringApplication               : Starting application using Java 17.0.4 on b1ed0a4336ef with PID 1 (started by root in /)
2022-11-02 17:05:34.560  INFO 1 --- [           main] o.s.boot.SpringApplication               : No active profile set, falling back to 1 default profile: "default"
2022-11-02 17:05:34.901  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.camunda.zeebe.spring.client.annotation.processor.AnnotationProcessorConfiguration' of type [io.camunda.zeebe.spring.client.annotation.processor.AnnotationProcessorConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.904  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'deploymentPostProcessor' of type [io.camunda.zeebe.spring.client.annotation.processor.ZeebeDeploymentAnnotationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.905  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration' of type [io.camunda.zeebe.spring.client.ZeebeClientSpringConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.908  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'commandExceptionHandlingStrategy' of type [io.camunda.zeebe.spring.client.jobhandling.DefaultCommandExceptionHandlingStrategy] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.909  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'secretStore' of type [io.camunda.connector.api.secret.SecretStore] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.982  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zeebe.client-io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties' of type [io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.984  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration' of type [io.camunda.zeebe.spring.client.config.ZeebeClientStarterAutoConfiguration$$EnhancerBySpringCGLIB$$3ea9abc2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.989  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zeebeJsonMapper' of type [io.camunda.zeebe.client.impl.ZeebeObjectMapper] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.990  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jobWorkerManager' of type [io.camunda.zeebe.spring.client.jobhandling.JobWorkerManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.991  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'outboundConnectorAnnotationProcessor' of type [io.camunda.zeebe.spring.client.annotation.processor.OutboundConnectorAnnotationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.992  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'propertyBasedZeebeWorkerValueCustomizer' of type [io.camunda.zeebe.spring.client.properties.PropertyBasedZeebeWorkerValueCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:34.993  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'zeebeWorkerPostProcessor' of type [io.camunda.zeebe.spring.client.annotation.processor.ZeebeWorkerAnnotationProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-02 17:05:35.061  INFO 1 --- [           main] i.c.z.s.c.ZeebeClientSpringConfiguration : Creating ZeebeClient using ZeebeClientBuilder [gatewayAddress: 0.0.0.0:26500
jobWorkerMaxJobsActive: 32
numJobWorkerExecutionThreads: 1
defaultJobWorkerName: null
defaultJobTimeout: PT5M
defaultJobPollInterval: PT0.1S
defaultMessageTimeToLive: PT1H
defaultRequestTimeout: PT10S
overrideAuthority: null
]
2022-11-02 17:05:35.282  INFO 1 --- [           main] a.p.OutboundConnectorAnnotationProcessor : Reading environment variables or parsing SPI to find connectors that are not Spring beans
2022-11-02 17:05:35.283  INFO 1 --- [           main] .u.o.OutboundConnectorRegistrationHelper : Parsing SPI to find connectors that are not Spring beans
2022-11-02 17:05:35.289  INFO 1 --- [           main] a.p.OutboundConnectorAnnotationProcessor : Found connectors that will be registered: [OutboundConnectorConfiguration{name='AWSSQS', type='io.camunda:aws-sqs:1', inputVariables=[authentication, queue], function=io.camunda.connector.SqsConnectorFunction@5a1c3cb4}]
2022-11-02 17:05:35.306  INFO 1 --- [           main] i.c.z.s.c.jobhandling.JobWorkerManager   : . Starting Zeebe worker: ZeebeWorkerValue{type='io.camunda:aws-sqs:1', name='AWSSQS', timeout=null, maxJobsActive=null, requestTimeout=null, pollInterval=null, autoComplete=true, fetchVariables=null, enabled=null, methodInfo=null}
2022-11-02 17:05:35.314  INFO 1 --- [           main] o.s.boot.SpringApplication               : Started application in 0.924 seconds (JVM running for 1.252)
2022-11-02 17:05:35.476  WARN 1 --- [ault-executor-1] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker AWSSQS and job type io.camunda:aws-sqs:1

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:470)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:434)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:467)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:26500
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2022-11-02 17:05:35.643  WARN 1 --- [ault-executor-1] io.camunda.zeebe.client.job.poller       : Failed to activate jobs for worker AWSSQS and job type io.camunda:aws-sqs:1

io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /0.0.0.0:26500
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Dockerfile for reference:
```
FROM eclipse-temurin:17.0.4_8-jre
RUN mkdir /opt/app

COPY target/connector-runtime-0.3.0-SNAPSHOT-with-dependencies.jar /opt/app
COPY target/connector-sqs-0.3.0-SNAPSHOT-with-dependencies.jar /opt/app

# Using entry point to allow downstream images to add JVM arguments using CMD
ENTRYPOINT ["java", "-cp", "/opt/app/*", "org.springframework.boot.loader.JarLauncher"]
```

**Comment by igpetrov** [comment]
Was able to run container in self-managed with https://github.com/camunda/camunda-platform

```
connectors: # https://docs.camunda.io/docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview/
    image: runtime222:${CAMUNDA_CONNECTORS_VERSION:-999.2.0}
    container_name: connectors
    environment:
      - ZEEBE_ADDRESS=zeebe:26500
      - ZEEBE_INSECURE=true
      - ZEEBE_CLIENT_BROKER_GATEWAY_ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS=zeebe:26500
      - ZEEBE_CLIENT_SECURITY_PLAINTEXT=true
    env_file: connector-secrets.txt
    networks:
      - camunda-platform
    depends_on:
      - zeebe
```

**Comment by tmetzke** [comment]
Thanks for this, @igpetrov, that was really helpful!
Closing as superseded by #223.

**Pull request closed without merging**
